# Generated by Django 5.2 on 2026-08-02 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Federation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_para', models.BooleanField(default=False)),
                ('is_championship', models.BooleanField(default=False)),
                ('is_general', models.BooleanField(default=False)),
                ('national_id', models.CharField(blank=True, max_length=30, null=True)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=10, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FederationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('president', 'رئیس هیات'), ('miss', 'نائب رئیس هیات'), ('vice', 'دبیر هیات')], default='president', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='federations.federation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='federation_positions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
