# Generated by Django 5.2 on 2026-08-02 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_type', models.CharField(choices=[('msy', 'دولتی ورزش و جوانان'), ('private', 'خصوصی (ماده 5)'), ('governmental', 'دولتی سایر ارگان ها')], default='msy', max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('geo_type', models.CharField(choices=[('rural', 'روستایی'), ('urban', 'شهری')], default='urban', max_length=30)),
                ('district', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=11)),
                ('area', models.FloatField(blank=True, null=True)),
                ('hall_area', models.FloatField(blank=True, null=True)),
                ('land_area', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sport_type', models.CharField(blank=True, max_length=255)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_contract', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacilityContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_serial', models.CharField(blank=True, max_length=30, null=True)),
                ('contractor_name', models.CharField(max_length=255)),
                ('contractor_seen_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contractor_phone', models.CharField(blank=True, max_length=11, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='facility_contracts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='facilities.facility')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FacilityLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_serial', models.CharField(blank=True, max_length=30, null=True)),
                ('holder_name', models.CharField(max_length=255)),
                ('is_renewal', models.BooleanField(default=False)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('license_file', models.FileField(blank=True, null=True, upload_to='facility_licenses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='facilities.facility')),
            ],
            options={
                'ordering': ['-issue_date'],
            },
        ),
    ]
