# Generated by Django 5.2 on 2026-08-02 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('seen_code', models.CharField(blank=True, max_length=10)),
                ('gender', models.CharField(choices=[('male', 'آقا'), ('female', 'خانم')], max_length=10)),
                ('phone', models.CharField(blank=True, max_length=11)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='champions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='champions', to='federations.federation')),
            ],
        ),
        migrations.CreateModel(
            name='Medals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medal_type', models.CharField(choices=[('gold', 'طلا'), ('silver', 'نقره'), ('bronze', 'برنز')], max_length=10)),
                ('competition_name', models.CharField(max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medals', to='champions.champion')),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
    ]
