# Generated by Django 5.2 on 2026-08-02 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('federations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Athletes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('federation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to='federations.federation')),
            ],
            options={
                'ordering': ['-year', '-month', 'federation'],
            },
        ),
    ]
